#!/usr/bin/env ruby

# Generate config/secret.yml

require 'securerandom'

SECRET_PATH = "config/secrets.yml"

exit 0 if File.exist?(SECRET_PATH)

secrets = 4.times.map { SecureRandom.hex(64) }
File.open(SECRET_PATH, 'w') {|f| f << DATA.read % secrets }

__END__
---
# Generated with script/bootstrap_secret
development:
  secret_key_base: %s

test:
  key_base: %s
